services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80" # Web UI Pi-hole di port 8080
    environment:
      TZ: "Asia/Jakarta"
      WEBPASSWORD: "palkiapihole" # Ganti dengan password kamu
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

