services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - ./data/configs:/app/data/configs
      - ./data/icons:/app/public/icons
      - ./data/storage:/data
      - /var/run/docker.sock:/var/run/docker.sock
