services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - "5232:5232"
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - USER=admin
      - PASSWORD=lohelohe

  infcloud:
    image: ckulka/infcloud
    container_name: infcloud
    ports:
      - "8100:80"
    restart: unless-stopped
