services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard-home
    ports:
      # Port DNS (WAJIB ADA)
      - "53:53/tcp"
      - "53:53/udp"
      # Port web interface (default AdGuard: 3000 after setup)
      - "8080:3000/tcp"
      # Port setup awal (hanya dibutuhkan sekali, bisa di-comment setelah setup)
      # - "3002:3000/tcp"
      # Port 80 & 443 di-nonaktifkan karena di-handle oleh NPM
      # - "80:80/tcp"
      # - "443:443/tcp"
      # Port opsional
      # - "67:67/udp"   # DHCP
      # - "68:68/udp"   # DHCP
      # - "853:853/tcp" # DNS-over-TLS
    volumes:
      - ./adguard_work:/opt/adguardhome/work
      - ./adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - palkia_network

networks:
  palkia_network:
    external: true

