- Dev:
    - GitHub:
        - icon: github
          href: https://github.com/
    - Docker Hub:
        - icon: docker
          href: https://hub.docker.com/
    - Selfhosted Icons:
        - icon: si-simpleicons
          href: https://selfh.st/icons/

- Media:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/
    - Reddit:
        - icon: reddit
          href: https://reddit.com/

- Tools:
    - ChatGPT:
        - icon: openai
          href: https://chat.openai.com/
    - Claude:
        - icon: si-anthropic
          href: https://claude.ai/
