- Monitor:
  - Uptime Kuma:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/uptime-kuma.png
      href: http://10.20.30.100:3001
      description: Uptime monitoring
      server: my-docker
      container: uptime-kuma
      widget:
        type: iframe
        src: http://10.20.30.100:3001/status/palkia-server
        classes: h-96
- Core:
  - Portainer:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png
      href: http://10.20.30.100:9000
      description: Docker management
      server: my-docker
      container: portainer

  - Nginx Proxy Manager:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nginx-proxy-manager.png
      href: http://10.20.30.100:81
      description: Reverse proxy + SSL
      server: my-docker
      container: nginx-proxy-manager

- Print:
  - CUPS Print Server:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cups.png
      href: http://10.20.30.100:631
      description: HP Ink Tank 115
      server: my-docker
      container: print-server
