- greeting:
    text_size: xl
    text: Palkia Server

- search:
    provider: google
    target: _blank
    focus: false

- resources:
    cpu: true
    memory: true
    disk: /
    label: System

- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
    locale: id-ID
